#!/usr/bin/env python3
"""Merge reviewed chapter DOCX files with Microsoft Word COM automation.

This Windows-only merge path asks Microsoft Word itself to insert each chapter
document. It avoids docxcompose/python-docx XML assembly so tables, images,
lists, code blocks, and paragraph formatting are preserved as closely as Word
can preserve them.
"""

from __future__ import annotations

import argparse
import csv
import platform
import shutil
import sys
import traceback
import zipfile
from dataclasses import dataclass
from datetime import date
from pathlib import Path
from typing import Any

from build_chapter_docx import (
    CHAPTER_SOURCES,
    DEFAULT_OUTPUT_DIR,
    DEFAULT_REFERENCE_DOC,
    DEFAULT_REVIEW_STATUS,
    REPO_ROOT,
    output_path_for,
    rel,
    resolve_repo_path,
    sha256_file,
)

DEFAULT_OUTPUT_DOCX = (
    REPO_ROOT / "book" / "output" / "docx" / "llm_data_analysis_course_full_word.docx"
)
DEFAULT_OUTPUT_PDF = REPO_ROOT / "book" / "output" / "pdf" / "llm_data_analysis_course_full.pdf"
DEFAULT_MANIFEST = REPO_ROOT / "book" / "output" / "docx" / "word_merge_manifest.csv"
DEFAULT_TITLE = "LLM 기반 데이터 분석 실무 입문"
DEFAULT_SUBTITLE = "챕터 0~15 통합 강의안"

WD_SECTION_BREAK_NEXT_PAGE = 2
WD_FORMAT_ORIGINAL_FORMATTING = 16
WD_COLLAPSE_END = 0
WD_HEADER_FOOTER_PRIMARY = 1
WD_EXPORT_FORMAT_PDF = 17
WD_FORMAT_DOCUMENT_DEFAULT = 16
WD_FIELD_PAGE = 33
WD_ALIGN_PARAGRAPH_CENTER = 1
WD_STATISTIC_PAGES = 2
WD_EXPORT_OPTIMIZE_FOR_PRINT = 0
WD_EXPORT_ALL_DOCUMENT = 0
WD_EXPORT_DOCUMENT_CONTENT = 0
WD_EXPORT_CREATE_HEADING_BOOKMARKS = 1


@dataclass
class ChapterPlan:
    chapter: int
    source: Path
    source_sha256: str
    status: str
    review_ok: bool
    hash_ok: bool
    issues: list[str]


@dataclass
class ChapterManifest:
    chapter: int
    source: Path
    source_sha256: str
    source_pages: int
    source_paragraphs: int
    source_tables: int
    source_inline_shapes: int
    integrated_start_page: int
    integrated_end_page: int
    integrated_section: int
    chapter_title: str
    status: str
    source_sha256_after: str


class UserFacingError(RuntimeError):
    """An error with a concise message intended for command-line users."""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Merge approved chapter DOCX files into DOCX/PDF using Microsoft Word COM."
    )
    parser.add_argument(
        "--chapters",
        type=int,
        nargs="+",
        choices=range(0, 16),
        metavar="0-15",
        help="Specific chapters to merge. Default: all chapters 0 through 15.",
    )
    parser.add_argument(
        "--input-dir",
        type=Path,
        default=DEFAULT_OUTPUT_DIR,
        help="Directory containing individual chapter DOCX files.",
    )
    parser.add_argument(
        "--reference-doc",
        type=Path,
        default=DEFAULT_REFERENCE_DOC,
        help="Common Word reference template.",
    )
    parser.add_argument(
        "--review-status",
        type=Path,
        default=DEFAULT_REVIEW_STATUS,
        help="Manual review approval CSV generated by build_chapter_docx.py.",
    )
    parser.add_argument(
        "--output-docx",
        type=Path,
        default=DEFAULT_OUTPUT_DOCX,
        help="Combined DOCX output path.",
    )
    parser.add_argument(
        "--output-pdf",
        type=Path,
        default=DEFAULT_OUTPUT_PDF,
        help="Combined PDF output path.",
    )
    parser.add_argument(
        "--manifest",
        type=Path,
        default=DEFAULT_MANIFEST,
        help="CSV manifest output path.",
    )
    parser.add_argument("--title", default=DEFAULT_TITLE, help="Cover-page title.")
    parser.add_argument("--subtitle", default=DEFAULT_SUBTITLE, help="Cover-page subtitle.")
    parser.add_argument("--no-cover", action="store_true", help="Do not add a cover page.")
    parser.add_argument("--no-toc", action="store_true", help="Do not add a Word TOC field.")
    parser.add_argument("--skip-pdf", action="store_true", help="Create DOCX only.")
    parser.add_argument("--visible", action="store_true", help="Show the Word window while merging.")
    parser.add_argument(
        "--force",
        action="store_true",
        help="Continue even when approval/hash checks fail. Intended for diagnostics.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Validate inputs and review status without starting Word or writing files.",
    )
    parser.add_argument(
        "--verbose",
        action="store_true",
        help="Print full traceback when an unexpected error occurs.",
    )
    return parser.parse_args()


def selected_chapters(values: list[int] | None) -> list[int]:
    return sorted(values if values else CHAPTER_SOURCES.keys())


def ensure_windows() -> None:
    """Fail early when Word COM cannot be used."""
    if platform.system() != "Windows":
        raise UserFacingError(
            "Microsoft Word COM automation requires Windows. "
            "Run --dry-run for input validation on non-Windows environments."
        )


def ensure_pywin32() -> tuple[Any, Any]:
    """Import pywin32 modules and provide a helpful installation hint."""
    try:
        import pythoncom
        import win32com.client
    except ImportError as exc:
        raise UserFacingError(
            "pywin32 is not installed. Run: python -m pip install -r requirements-docx.txt"
        ) from exc
    return pythoncom, win32com.client


def start_word_application(visible: bool) -> tuple[Any, Any, Any]:
    """Start an isolated Word instance with DispatchEx."""
    pythoncom, win32com_client = ensure_pywin32()
    pythoncom.CoInitialize()
    try:
        word = win32com_client.DispatchEx("Word.Application")
    except Exception as exc:  # noqa: BLE001
        pythoncom.CoUninitialize()
        raise UserFacingError(
            "[ERROR] Microsoft Word COM could not be started.\n"
            "Microsoft Word가 설치되어 있는지 확인하고, 열려 있는 Word 프로세스가 "
            "작업 파일을 잡고 있다면 종료한 뒤 다시 실행하세요."
        ) from exc

    word.Visible = bool(visible)
    word.DisplayAlerts = 0
    word.ScreenUpdating = bool(visible)
    return word, pythoncom, win32com_client


def validate_docx(path: Path) -> None:
    """Ensure a path points to a non-empty valid DOCX zip package."""
    if not path.exists():
        raise UserFacingError(f"DOCX file was not found: {rel(path)}")
    if path.stat().st_size == 0:
        raise UserFacingError(f"DOCX file is empty: {rel(path)}")
    if not zipfile.is_zipfile(path):
        raise UserFacingError(f"DOCX file is not a valid ZIP package: {rel(path)}")
    with zipfile.ZipFile(path) as archive:
        required = {"[Content_Types].xml", "word/document.xml"}
        missing = required.difference(archive.namelist())
    if missing:
        raise UserFacingError(f"DOCX package is missing required parts: {rel(path)}")


def load_review_status(path: Path) -> dict[int, dict[str, str]]:
    if not path.exists():
        raise UserFacingError(
            f"Review status CSV was not found: {rel(path)}\n"
            "Run python scripts/build_chapter_docx.py first."
        )
    rows: dict[int, dict[str, str]] = {}
    with path.open("r", encoding="utf-8-sig", newline="") as handle:
        for row in csv.DictReader(handle):
            try:
                rows[int(row.get("chapter", ""))] = row
            except ValueError:
                continue
    return rows


def verify_manual_approval(chapter: int, docx_path: Path, rows: dict[int, dict[str, str]]) -> ChapterPlan:
    """Check status=approved and matching DOCX hash for one chapter."""
    issues: list[str] = []
    row = rows.get(chapter)
    status = ""
    recorded_hash = ""
    if row is None:
        issues.append(f"Chapter {chapter:02d}: no review-status row")
    else:
        status = row.get("status", "").strip().lower()
        recorded_hash = row.get("docx_sha256", "").strip().lower()

    validate_docx(docx_path)
    actual_hash = sha256_file(docx_path)
    review_ok = status == "approved"
    hash_ok = bool(recorded_hash) and recorded_hash == actual_hash

    if not review_ok:
        issues.append(f"Chapter {chapter:02d}: status is {status or 'blank'}, not approved")
    if not recorded_hash:
        issues.append(f"Chapter {chapter:02d}: recorded DOCX hash is blank")
    elif not hash_ok:
        issues.append(
            f"Chapter {chapter:02d}: DOCX hash mismatch "
            f"(recorded={recorded_hash[:12]}, actual={actual_hash[:12]})"
        )

    return ChapterPlan(
        chapter=chapter,
        source=docx_path,
        source_sha256=actual_hash,
        status=status or "missing",
        review_ok=review_ok,
        hash_ok=hash_ok,
        issues=issues,
    )


def validate_inputs(
    chapters: list[int],
    input_dir: Path,
    reference_doc: Path,
    review_status: Path,
    force: bool,
) -> list[ChapterPlan]:
    """Validate template, chapter DOCX files, and review gate rows."""
    validate_docx(reference_doc)
    rows = load_review_status(review_status)
    plans: list[ChapterPlan] = []
    issues: list[str] = []

    for chapter in chapters:
        path = output_path_for(chapter, input_dir)
        plan = verify_manual_approval(chapter, path, rows)
        plans.append(plan)
        issues.extend(plan.issues)

    if issues and not force:
        details = "\n".join(f"- {issue}" for issue in issues)
        raise UserFacingError(
            "Manual review gate failed:\n"
            f"{details}\n\n"
            "각 챕터 DOCX를 Word에서 검수한 뒤 chapter_review_status.csv의 "
            "status를 approved로 변경하고, 해시가 현재 DOCX와 일치하는지 확인하세요. "
            "진단 목적으로만 계속하려면 --force를 사용하세요."
        )
    if issues and force:
        print("[WARN] --force used. Approval/hash issues are being ignored:")
        for issue in issues:
            print(f"       {issue}")
    return plans


def print_dry_run(
    plans: list[ChapterPlan],
    reference_doc: Path,
    output_docx: Path,
    output_pdf: Path,
    skip_pdf: bool,
) -> None:
    print("[INFO] Merge engine: Microsoft Word COM")
    print("[INFO] Microsoft Word detected: not started during dry run")
    print(f"[INFO] Input chapters: {len(plans)}")
    print(f"[INFO] Reference DOCX: {rel(reference_doc)}")
    print(f"[INFO] Output DOCX: {rel(output_docx)}")
    print(f"[INFO] Output PDF: {'skipped' if skip_pdf else rel(output_pdf)}")
    print()
    for index, plan in enumerate(plans, start=1):
        hash_text = "hash OK" if plan.hash_ok else "hash check bypassed"
        print(f"{index:02d}. Chapter {plan.chapter:02d}: {plan.status}, {hash_text}")
    print("\n[OK] Dry run completed. No file was written.")


def word_version(word: Any) -> str:
    try:
        return str(word.Version)
    except Exception:  # noqa: BLE001
        return "unknown"


def close_document(doc: Any | None, save_changes: bool = False) -> None:
    if doc is not None:
        try:
            doc.Close(SaveChanges=save_changes)
        except Exception:  # noqa: BLE001
            pass


def cleanup_word(word: Any | None, pythoncom: Any | None) -> None:
    """Quit only the Word instance created by this script."""
    if word is not None:
        try:
            word.Quit()
        except Exception:  # noqa: BLE001
            pass
    if pythoncom is not None:
        try:
            pythoncom.CoUninitialize()
        except Exception:  # noqa: BLE001
            pass


def prepare_master_document(word: Any, reference_doc: Path, tmp_docx: Path) -> Any:
    """Open a temporary copy of the reference DOCX and clear its body."""
    tmp_docx.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(reference_doc, tmp_docx)
    doc = word.Documents.Open(str(tmp_docx), ReadOnly=False, AddToRecentFiles=False)
    clear_document_body(doc)
    configure_document_layout(doc)
    return doc


def clear_document_body(doc: Any) -> None:
    """Remove body content while keeping document styles and section setup."""
    body = doc.Range(0, max(0, doc.Content.End - 1))
    body.Delete()


def end_range(doc: Any) -> Any:
    target = doc.Content
    target.Collapse(WD_COLLAPSE_END)
    return target


def insert_section_break(doc: Any) -> None:
    target = end_range(doc)
    target.InsertBreak(WD_SECTION_BREAK_NEXT_PAGE)
    target.Collapse(WD_COLLAPSE_END)


def add_paragraph(doc: Any, text: str = "") -> Any:
    target = end_range(doc)
    target.InsertAfter(text)
    target.InsertParagraphAfter()
    return doc.Paragraphs(doc.Paragraphs.Count)


def set_paragraph_text_style(paragraph: Any, size: int, bold: bool = False, center: bool = False) -> None:
    paragraph.Range.Font.Size = size
    paragraph.Range.Font.Bold = -1 if bold else 0
    if center:
        paragraph.Alignment = WD_ALIGN_PARAGRAPH_CENTER


def add_cover_page(doc: Any, title: str, subtitle: str) -> None:
    """Create a simple cover page with title, subtitle, and date."""
    add_paragraph(doc)
    add_paragraph(doc)
    title_paragraph = add_paragraph(doc, title)
    set_paragraph_text_style(title_paragraph, 28, bold=True, center=True)
    subtitle_paragraph = add_paragraph(doc, subtitle)
    set_paragraph_text_style(subtitle_paragraph, 15, center=True)
    date_paragraph = add_paragraph(doc, f"생성일: {date.today().isoformat()}")
    set_paragraph_text_style(date_paragraph, 10, center=True)
    insert_section_break(doc)


def add_toc(doc: Any) -> None:
    """Add a Word table of contents field for Heading 1 through 3."""
    heading = add_paragraph(doc, "목차")
    try:
        heading.Style = "Heading 1"
    except Exception:  # noqa: BLE001
        set_paragraph_text_style(heading, 20, bold=True)

    toc_range = end_range(doc)
    doc.TablesOfContents.Add(
        Range=toc_range,
        UseHeadingStyles=True,
        UpperHeadingLevel=1,
        LowerHeadingLevel=3,
        UseHyperlinks=True,
        HidePageNumbersInWeb=False,
        UseOutlineLevels=True,
        RightAlignPageNumbers=True,
    )


def configure_document_layout(doc: Any) -> None:
    """Normalize header/footer and page-number behavior across the document."""
    try:
        doc.PageSetup.OddAndEvenPagesHeaderFooter = False
    except Exception:  # noqa: BLE001
        pass
    for section in doc.Sections:
        try:
            section.PageSetup.DifferentFirstPageHeaderFooter = False
        except Exception:  # noqa: BLE001
            pass
        link_section_headers_and_footers(section)
        continue_page_numbering(section)
    ensure_page_number_field(doc)


def link_section_headers_and_footers(section: Any) -> None:
    """Link primary headers and footers to the previous section when possible."""
    try:
        section.Headers(WD_HEADER_FOOTER_PRIMARY).LinkToPrevious = True
    except Exception:  # noqa: BLE001
        pass
    try:
        section.Footers(WD_HEADER_FOOTER_PRIMARY).LinkToPrevious = True
    except Exception:  # noqa: BLE001
        pass


def continue_page_numbering(section: Any) -> None:
    """Prevent a section from restarting page numbering."""
    try:
        page_numbers = section.Footers(WD_HEADER_FOOTER_PRIMARY).PageNumbers
        page_numbers.RestartNumberingAtSection = False
    except Exception:  # noqa: BLE001
        pass


def ensure_page_number_field(doc: Any) -> None:
    """Add a centered PAGE field when the primary footer has no fields."""
    try:
        footer = doc.Sections(1).Footers(WD_HEADER_FOOTER_PRIMARY)
        if footer.Range.Fields.Count > 0:
            return
        footer.Range.ParagraphFormat.Alignment = WD_ALIGN_PARAGRAPH_CENTER
        footer.Range.Fields.Add(footer.Range, WD_FIELD_PAGE)
    except Exception:  # noqa: BLE001
        pass


def source_range_without_final_mark(source_doc: Any) -> Any:
    source_range = source_doc.Content.Duplicate
    if source_range.End > source_range.Start:
        source_range.End = source_range.End - 1
    return source_range


def first_nonblank_paragraph(source_doc: Any, fallback: str) -> str:
    for paragraph in source_doc.Paragraphs:
        text = paragraph.Range.Text.replace("\r", "").strip()
        if text:
            return text
    return fallback


def copy_chapter_with_word(word: Any, master_doc: Any, plan: ChapterPlan) -> ChapterManifest:
    """Open a source DOCX read-only and paste its content using original formatting."""
    source_doc = None
    before_hash = plan.source_sha256
    try:
        source_doc = word.Documents.Open(
            str(plan.source),
            ReadOnly=True,
            AddToRecentFiles=False,
            ConfirmConversions=False,
        )
        source_doc.Repaginate()
        source_pages = int(source_doc.ComputeStatistics(WD_STATISTIC_PAGES))
        source_paragraphs = int(source_doc.Paragraphs.Count)
        source_tables = int(source_doc.Tables.Count)
        source_inline_shapes = int(source_doc.InlineShapes.Count)
        title = first_nonblank_paragraph(source_doc, f"Chapter {plan.chapter:02d}")

        if document_has_substantive_content(master_doc):
            insert_section_break(master_doc)
        configure_document_layout(master_doc)
        integrated_section = int(master_doc.Sections.Count)
        start_page = current_end_page(master_doc)

        print(f"[INFO] Inserting Chapter {plan.chapter:02d}")
        print(f"       source pages: {source_pages}")
        print(f"       tables: {source_tables}")
        print(f"       inline shapes: {source_inline_shapes}")
        print(f"       integrated start page: {start_page}")
        print(f"       integrated section: {integrated_section}")

        source_range = source_range_without_final_mark(source_doc)
        source_range.Copy()
        target = end_range(master_doc)
        target.PasteAndFormat(WD_FORMAT_ORIGINAL_FORMATTING)

        master_doc.Repaginate()
        end_page = current_end_page(master_doc)
        after_hash = sha256_file(plan.source)

        return ChapterManifest(
            chapter=plan.chapter,
            source=plan.source,
            source_sha256=before_hash,
            source_pages=source_pages,
            source_paragraphs=source_paragraphs,
            source_tables=source_tables,
            source_inline_shapes=source_inline_shapes,
            integrated_start_page=start_page,
            integrated_end_page=end_page,
            integrated_section=integrated_section,
            chapter_title=title,
            status="ok",
            source_sha256_after=after_hash,
        )
    except Exception as exc:  # noqa: BLE001
        raise UserFacingError(
            f"Failed to insert Chapter {plan.chapter:02d} from {rel(plan.source)}. "
            "파일이 Word에서 열려 있거나 손상되지 않았는지 확인하세요."
        ) from exc
    finally:
        close_document(source_doc, save_changes=False)


def document_has_substantive_content(doc: Any) -> bool:
    """Return True when the document body has visible text or inserted objects."""
    try:
        text = doc.Content.Text.replace("\r", "").replace("\x07", "").strip()
        return bool(text or doc.Tables.Count or doc.InlineShapes.Count or doc.TablesOfContents.Count)
    except Exception:  # noqa: BLE001
        return True


def current_end_page(doc: Any) -> int:
    doc.Repaginate()
    return int(doc.ComputeStatistics(WD_STATISTIC_PAGES))


def update_all_fields(doc: Any) -> None:
    """Repaginate and update document, TOC, header, and footer fields."""
    doc.Repaginate()
    try:
        doc.Fields.Update()
    except Exception:  # noqa: BLE001
        pass
    for toc in doc.TablesOfContents:
        try:
            toc.Update()
        except Exception:  # noqa: BLE001
            pass
    for section in doc.Sections:
        for collection_name in ("Headers", "Footers"):
            collection = getattr(section, collection_name)
            for index in (1, 2, 3):
                try:
                    collection(index).Range.Fields.Update()
                except Exception:  # noqa: BLE001
                    pass
    doc.Repaginate()


def validate_chapter_titles(doc: Any, manifests: list[ChapterManifest]) -> list[str]:
    """Perform lightweight post-merge checks through Word COM."""
    issues: list[str] = []
    previous_page = 0
    for item in manifests:
        if item.integrated_start_page <= previous_page:
            issues.append(
                f"Chapter {item.chapter:02d}: start page did not increase "
                f"({item.integrated_start_page} <= {previous_page})"
            )
        previous_page = item.integrated_start_page
        if item.source_sha256 != item.source_sha256_after:
            issues.append(f"Chapter {item.chapter:02d}: source DOCX changed during merge")
        if not text_exists(doc, item.chapter_title):
            issues.append(f"Chapter {item.chapter:02d}: title not found after merge: {item.chapter_title}")
    if doc.TablesOfContents.Count == 0:
        issues.append("Table of contents was not created")
    return issues


def text_exists(doc: Any, text: str) -> bool:
    if not text:
        return False
    finder = doc.Content.Find
    finder.ClearFormatting()
    return bool(finder.Execute(FindText=text, Forward=True, MatchCase=False, MatchWholeWord=False))


def build_merge_manifest(path: Path, manifests: list[ChapterManifest]) -> None:
    """Write the merge manifest CSV."""
    path.parent.mkdir(parents=True, exist_ok=True)
    fields = [
        "chapter",
        "source",
        "source_sha256",
        "source_pages",
        "source_paragraphs",
        "source_tables",
        "source_inline_shapes",
        "integrated_start_page",
        "integrated_end_page",
        "integrated_section",
        "chapter_title",
        "status",
    ]
    tmp_path = path.with_name(path.stem + ".tmp.csv")
    with tmp_path.open("w", encoding="utf-8-sig", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields)
        writer.writeheader()
        for item in manifests:
            writer.writerow(
                {
                    "chapter": item.chapter,
                    "source": item.source.name,
                    "source_sha256": item.source_sha256,
                    "source_pages": item.source_pages,
                    "source_paragraphs": item.source_paragraphs,
                    "source_tables": item.source_tables,
                    "source_inline_shapes": item.source_inline_shapes,
                    "integrated_start_page": item.integrated_start_page,
                    "integrated_end_page": item.integrated_end_page,
                    "integrated_section": item.integrated_section,
                    "chapter_title": item.chapter_title,
                    "status": item.status,
                }
            )
    tmp_path.replace(path)


def save_docx_temp(doc: Any, output_docx: Path) -> Path:
    """Save to a temporary DOCX. Replacement happens after Word closes it."""
    output_docx.parent.mkdir(parents=True, exist_ok=True)
    tmp_docx = output_docx.with_name(output_docx.stem + ".tmp.docx")
    if tmp_docx.exists():
        tmp_docx.unlink()
    doc.SaveAs2(str(tmp_docx), FileFormat=WD_FORMAT_DOCUMENT_DEFAULT)
    return tmp_docx


def export_pdf_temp(doc: Any, output_pdf: Path) -> Path:
    """Export a PDF through Word to a temporary path."""
    output_pdf.parent.mkdir(parents=True, exist_ok=True)
    tmp_pdf = output_pdf.with_name(output_pdf.stem + ".tmp.pdf")
    if tmp_pdf.exists():
        tmp_pdf.unlink()
    doc.ExportAsFixedFormat(
        OutputFileName=str(tmp_pdf),
        ExportFormat=WD_EXPORT_FORMAT_PDF,
        OpenAfterExport=False,
        OptimizeFor=WD_EXPORT_OPTIMIZE_FOR_PRINT,
        Range=WD_EXPORT_ALL_DOCUMENT,
        Item=WD_EXPORT_DOCUMENT_CONTENT,
        IncludeDocProps=True,
        KeepIRM=True,
        CreateBookmarks=WD_EXPORT_CREATE_HEADING_BOOKMARKS,
        DocStructureTags=True,
        BitmapMissingFonts=True,
        UseISO19005_1=False,
    )
    if not tmp_pdf.exists() or tmp_pdf.stat().st_size == 0:
        raise UserFacingError(
            "Word PDF export failed or produced an empty file. "
            "출력 PDF가 열려 있지 않은지 확인한 뒤 다시 실행하세요."
        )
    return tmp_pdf


def replace_output_files(tmp_docx: Path, output_docx: Path, tmp_pdf: Path | None, output_pdf: Path) -> None:
    """Replace final outputs after Word has released temporary files."""
    validate_docx(tmp_docx)
    tmp_docx.replace(output_docx)
    validate_docx(output_docx)
    if tmp_pdf is not None:
        if not tmp_pdf.exists() or tmp_pdf.stat().st_size == 0:
            raise UserFacingError("Temporary PDF export is missing or empty.")
        tmp_pdf.replace(output_pdf)


def merge_with_word(
    plans: list[ChapterPlan],
    reference_doc: Path,
    output_docx: Path,
    output_pdf: Path,
    manifest_path: Path,
    title: str,
    subtitle: str,
    cover: bool,
    toc: bool,
    skip_pdf: bool,
    visible: bool,
) -> list[ChapterManifest]:
    """Run the complete Word COM merge and output DOCX/PDF/manifest files."""
    ensure_windows()
    word = None
    master_doc = None
    pythoncom = None
    tmp_work_docx = output_docx.with_name(output_docx.stem + ".work.tmp.docx")
    tmp_final_docx: Path | None = None
    tmp_final_pdf: Path | None = None
    manifests: list[ChapterManifest] = []
    try:
        word, pythoncom, _ = start_word_application(visible)
        print("[INFO] Merge engine: Microsoft Word COM")
        print(f"[INFO] Microsoft Word detected: {word_version(word)}")
        master_doc = prepare_master_document(word, reference_doc, tmp_work_docx)

        if cover:
            add_cover_page(master_doc, title, subtitle)
        if toc:
            add_toc(master_doc)

        for plan in plans:
            manifests.append(copy_chapter_with_word(word, master_doc, plan))

        configure_document_layout(master_doc)
        update_all_fields(master_doc)
        issues = validate_chapter_titles(master_doc, manifests)
        if issues:
            print("[WARN] Post-merge validation warnings:")
            for issue in issues:
                print(f"       {issue}")

        update_all_fields(master_doc)
        tmp_final_docx = save_docx_temp(master_doc, output_docx)
        if not skip_pdf:
            update_all_fields(master_doc)
            tmp_final_pdf = export_pdf_temp(master_doc, output_pdf)

        build_merge_manifest(manifest_path, manifests)
        close_document(master_doc, save_changes=False)
        master_doc = None
        replace_output_files(tmp_final_docx, output_docx, tmp_final_pdf, output_pdf)
        return manifests
    finally:
        close_document(master_doc, save_changes=False)
        cleanup_word(word, pythoncom)
        if tmp_work_docx.exists():
            try:
                tmp_work_docx.unlink()
            except OSError:
                pass


def print_next_steps(output_docx: Path, output_pdf: Path, skip_pdf: bool) -> None:
    print()
    print(f"[OK] Combined DOCX created: {rel(output_docx)}")
    if skip_pdf:
        print("[INFO] PDF export skipped.")
    else:
        print(f"[OK] Combined PDF created: {rel(output_pdf)}")
    print("[NEXT] Open the combined DOCX and compare the following pages with the source chapter files:")
    print("- Chapter 01 tables and diagrams")
    print("- Chapter 08 project question map")
    print("- Chapter 14 Airflow screenshots")
    print("- Chapter 15 final project tables")


def main() -> int:
    args = parse_args()
    chapters = selected_chapters(args.chapters)
    input_dir = resolve_repo_path(args.input_dir).resolve()
    reference_doc = resolve_repo_path(args.reference_doc).resolve()
    review_status = resolve_repo_path(args.review_status).resolve()
    output_docx = resolve_repo_path(args.output_docx).resolve()
    output_pdf = resolve_repo_path(args.output_pdf).resolve()
    manifest_path = resolve_repo_path(args.manifest).resolve()

    try:
        plans = validate_inputs(
            chapters=chapters,
            input_dir=input_dir,
            reference_doc=reference_doc,
            review_status=review_status,
            force=args.force,
        )

        if args.dry_run:
            print_dry_run(plans, reference_doc, output_docx, output_pdf, args.skip_pdf)
            return 0

        merge_with_word(
            plans=plans,
            reference_doc=reference_doc,
            output_docx=output_docx,
            output_pdf=output_pdf,
            manifest_path=manifest_path,
            title=args.title,
            subtitle=args.subtitle,
            cover=not args.no_cover,
            toc=not args.no_toc,
            skip_pdf=args.skip_pdf,
            visible=args.visible,
        )
        print_next_steps(output_docx, output_pdf, args.skip_pdf)
    except UserFacingError as exc:
        print(f"[ERROR] {exc}", file=sys.stderr)
        if args.verbose:
            traceback.print_exc()
        return 1
    except Exception as exc:  # noqa: BLE001
        print(f"[ERROR] Unexpected failure: {exc}", file=sys.stderr)
        if args.verbose:
            traceback.print_exc()
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
