#!/usr/bin/env python3
"""Merge manually approved chapter DOCX files into one combined Word document.

This script enforces a review gate. By default, every selected chapter must have
``status=approved`` in ``book/output/docx/chapter_review_status.csv`` and the
recorded DOCX SHA-256 hash must match the current file.

The combined document includes a cover page and a Word TOC field. After opening the
result in Microsoft Word, press Ctrl+A and F9 to refresh the table of contents and
all fields.
"""

from __future__ import annotations

import argparse
import csv
import sys
import tempfile
import zipfile
from datetime import date
from pathlib import Path

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.shared import Pt, RGBColor

from build_chapter_docx import (
    CHAPTER_SOURCES,
    DEFAULT_OUTPUT_DIR,
    DEFAULT_REFERENCE_DOC,
    DEFAULT_REVIEW_STATUS,
    REPO_ROOT,
    output_path_for,
    rel,
    resolve_repo_path,
    sha256_file,
)

DEFAULT_OUTPUT = REPO_ROOT / "book" / "output" / "docx" / "llm_data_analysis_course_full.docx"
DEFAULT_TITLE = "LLM 기반 데이터 분석 실무 입문"
DEFAULT_SUBTITLE = "챕터 0~15 통합 강의안"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Merge manually approved chapter DOCX files into one combined DOCX."
    )
    parser.add_argument(
        "--chapters",
        type=int,
        nargs="+",
        choices=range(0, 16),
        metavar="0-15",
        help="Specific chapters to merge. Default: all chapters 0 through 15.",
    )
    parser.add_argument(
        "--input-dir",
        type=Path,
        default=DEFAULT_OUTPUT_DIR,
        help="Directory containing individual chapter DOCX files.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help="Combined DOCX output path.",
    )
    parser.add_argument(
        "--reference-doc",
        type=Path,
        default=DEFAULT_REFERENCE_DOC,
        help="Common Word template used as the merge master.",
    )
    parser.add_argument(
        "--review-status",
        type=Path,
        default=DEFAULT_REVIEW_STATUS,
        help="Manual review approval CSV generated by build_chapter_docx.py.",
    )
    parser.add_argument("--title", default=DEFAULT_TITLE, help="Cover-page title.")
    parser.add_argument("--subtitle", default=DEFAULT_SUBTITLE, help="Cover-page subtitle.")
    parser.add_argument(
        "--no-cover",
        action="store_true",
        help="Do not add the generated cover page.",
    )
    parser.add_argument(
        "--no-toc",
        action="store_true",
        help="Do not add the Word table-of-contents field.",
    )
    parser.add_argument(
        "--no-page-breaks",
        action="store_true",
        help="Do not insert page breaks between chapter files.",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Merge even when manual approval or hash checks fail. Use only for diagnostics.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Validate inputs and print the merge plan without writing the combined DOCX.",
    )
    return parser.parse_args()


def selected_chapters(values: list[int] | None) -> list[int]:
    return sorted(values if values else CHAPTER_SOURCES.keys())


def validate_docx(path: Path) -> None:
    if not path.exists() or path.stat().st_size == 0:
        raise FileNotFoundError(f"Missing or empty DOCX: {rel(path)}")
    if not zipfile.is_zipfile(path):
        raise RuntimeError(f"Invalid DOCX package: {rel(path)}")


def load_review_status(path: Path) -> dict[int, dict[str, str]]:
    if not path.exists():
        raise FileNotFoundError(
            f"Review status CSV was not found: {rel(path)}\n"
            "Run python scripts/build_chapter_docx.py first."
        )
    rows: dict[int, dict[str, str]] = {}
    with path.open("r", encoding="utf-8-sig", newline="") as handle:
        for row in csv.DictReader(handle):
            try:
                rows[int(row.get("chapter", ""))] = row
            except ValueError:
                continue
    return rows


def verify_manual_approval(
    chapter: int,
    docx_path: Path,
    review_rows: dict[int, dict[str, str]],
) -> list[str]:
    issues: list[str] = []
    row = review_rows.get(chapter)
    if row is None:
        return [f"Chapter {chapter:02d}: no review-status row"]

    if row.get("status", "").strip().lower() != "approved":
        issues.append(
            f"Chapter {chapter:02d}: status is {row.get('status', '').strip() or 'blank'}, not approved"
        )

    recorded_hash = row.get("docx_sha256", "").strip().lower()
    actual_hash = sha256_file(docx_path)
    if not recorded_hash:
        issues.append(f"Chapter {chapter:02d}: recorded DOCX hash is blank")
    elif recorded_hash != actual_hash:
        issues.append(
            f"Chapter {chapter:02d}: DOCX changed after review "
            f"(recorded={recorded_hash[:12]}, actual={actual_hash[:12]})"
        )
    return issues


def ensure_dependencies() -> type:
    try:
        from docxcompose.composer import Composer
    except ImportError as exc:
        raise RuntimeError(
            "docxcompose is not installed. Run: pip install -r requirements-docx.txt"
        ) from exc
    return Composer


def clear_document_body(document: Document) -> None:
    body = document._element.body
    for child in list(body):
        if child.tag != qn("w:sectPr"):
            body.remove(child)


def add_toc_field(paragraph) -> None:
    paragraph.alignment = WD_ALIGN_PARAGRAPH.LEFT
    run = paragraph.add_run()
    begin = OxmlElement("w:fldChar")
    begin.set(qn("w:fldCharType"), "begin")
    instr = OxmlElement("w:instrText")
    instr.set(qn("xml:space"), "preserve")
    instr.text = ' TOC \\o "1-3" \\h \\z \\u '
    separate = OxmlElement("w:fldChar")
    separate.set(qn("w:fldCharType"), "separate")
    placeholder = OxmlElement("w:t")
    placeholder.text = "목차를 업데이트하려면 Word에서 Ctrl+A를 누른 뒤 F9를 누르세요."
    end = OxmlElement("w:fldChar")
    end.set(qn("w:fldCharType"), "end")
    run._r.extend([begin, instr, separate, placeholder, end])


def request_field_updates(document: Document) -> None:
    settings = document.settings._element
    node = settings.find(qn("w:updateFields"))
    if node is None:
        node = OxmlElement("w:updateFields")
        settings.append(node)
    node.set(qn("w:val"), "true")


def add_front_matter(document: Document, title: str, subtitle: str, cover: bool, toc: bool) -> None:
    if cover:
        paragraph = document.add_paragraph(style="Title")
        paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER
        paragraph.add_run(title)
        paragraph = document.add_paragraph(style="Subtitle")
        paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER
        paragraph.add_run(subtitle)
        paragraph = document.add_paragraph()
        paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = paragraph.add_run(f"생성일: {date.today().isoformat()}")
        run.font.size = Pt(10)
        run.font.color.rgb = RGBColor(89, 89, 89)
        document.add_page_break()

    if toc:
        document.add_paragraph("목차", style="Heading 1")
        toc_paragraph = document.add_paragraph()
        add_toc_field(toc_paragraph)
        document.add_page_break()


def merge_documents(
    input_paths: list[Path],
    output: Path,
    reference_doc: Path,
    title: str,
    subtitle: str,
    cover: bool,
    toc: bool,
    page_breaks: bool,
) -> None:
    Composer = ensure_dependencies()
    master = Document(str(reference_doc))
    clear_document_body(master)
    add_front_matter(master, title, subtitle, cover, toc)
    request_field_updates(master)

    composer = Composer(master)
    for index, source in enumerate(input_paths):
        if index > 0 and page_breaks:
            composer.doc.add_page_break()
        composer.append(Document(str(source)))

    output.parent.mkdir(parents=True, exist_ok=True)
    temp_output = output.with_name(output.stem + ".tmp.docx")
    if temp_output.exists():
        temp_output.unlink()
    composer.save(str(temp_output))
    validate_docx(temp_output)
    temp_output.replace(output)
    validate_docx(output)


def main() -> int:
    args = parse_args()
    chapters = selected_chapters(args.chapters)
    input_dir = resolve_repo_path(args.input_dir).resolve()
    output = resolve_repo_path(args.output).resolve()
    reference_doc = resolve_repo_path(args.reference_doc).resolve()
    review_status = resolve_repo_path(args.review_status).resolve()

    try:
        validate_docx(reference_doc)
        review_rows = load_review_status(review_status)
        inputs: list[Path] = []
        approval_issues: list[str] = []

        for chapter in chapters:
            path = output_path_for(chapter, input_dir)
            validate_docx(path)
            inputs.append(path)
            approval_issues.extend(verify_manual_approval(chapter, path, review_rows))

        if approval_issues and not args.force:
            details = "\n".join(f"- {issue}" for issue in approval_issues)
            raise RuntimeError(
                "Manual review gate failed:\n"
                f"{details}\n\n"
                "Open each chapter DOCX, complete visual review, and set status=approved in "
                f"{rel(review_status)}. Rebuilds reset approval to pending."
            )
        if approval_issues and args.force:
            print("[WARN] --force used. Manual approval/hash issues are being ignored:")
            for issue in approval_issues:
                print(f"  - {issue}")

        print("[INFO] Merge order:")
        for index, path in enumerate(inputs, start=1):
            print(f"  {index:02d}. {rel(path)}")
        print(f"[INFO] Output: {rel(output)}")
        print(f"[INFO] Cover: {not args.no_cover}")
        print(f"[INFO] TOC field: {not args.no_toc}")
        print(f"[INFO] Page breaks between chapters: {not args.no_page_breaks}")

        if args.dry_run:
            print("\n[OK] Dry run completed. No file was written.")
            return 0

        merge_documents(
            input_paths=inputs,
            output=output,
            reference_doc=reference_doc,
            title=args.title,
            subtitle=args.subtitle,
            cover=not args.no_cover,
            toc=not args.no_toc,
            page_breaks=not args.no_page_breaks,
        )

        print(f"\n[OK] Combined DOCX created: {rel(output)}")
        print("[NEXT] Open the file in Microsoft Word, press Ctrl+A and F9, then inspect the full document.")

    except Exception as exc:  # noqa: BLE001
        print(f"[ERROR] {exc}", file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
